#version: '3'
#
#services:
#  web:
#    build:
#      context: .
#      dockerfile: docker/nginx/Dockerfile
#    ports:
#      - "8080:80"
#    volumes:
#      - .:/app/
#    links:
#      - php
#
#  php:
#    build:
#      context: .
#      dockerfile: docker/php/Dockerfile
#    volumes:
#      - .:/app/
#
#  db:
#    build:
#        context: .
#        dockerfile: docker/database/Dockerfile
#    ports:
#        - "5433:5432"
version: '3'
services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
    - "8080:80"
    - "443:443"
    volumes:
      - .:/app/
    links:
      - php
    networks:
      - nginx

  db:
    build:
      context: .
      dockerfile: docker/database/Dockerfile
    ports:
      - "5432:5432"
    networks:
      - pg-network
    volumes:
      - pg-data:/var/lib/postgresql/data

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/app/
    networks:
       - pg-network
       - nginx

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "5050:80"
    networks:
      - pg-network

networks:
  pg-network:
  nginx:
volumes:
  pg-data: